### ISSUE TITLE
Unable to compile "WarZone.pwn"

### ISSUE THREAD

**Issue by CEKIKOFGAMERS** [Revelts/SA-MP-WarZone#1]
D:\Server\SA-MP-WarZone\pawno\include\chrono.inc(75) : error 075: input line too long (after substitutions)
D:\Server\SA-MP-WarZone\pawno\include\chrono.inc(77) : error 010: invalid function or declaration
D:\Server\SA-MP-WarZone\pawno\include\nex-ac.inc(2206) : error 017: undefined symbol "STREAMER_PICKUP_SD"
D:\Server\SA-MP-WarZone\pawno\include\nex-ac.inc(2208) : warning 202: number of arguments does not match definition
D:\Server\SA-MP-WarZone\pawno\include\nex-ac.inc(2208) : warning 202: number of arguments does not match definition
D:\Server\SA-MP-WarZone\pawno\include\nex-ac.inc(2206) : warning 203: symbol is never used: "priority"
D:\Server\SA-MP-WarZone\pawno\include\nex-ac.inc(2206) : warning 203: symbol is never used: "areaid"
D:\Server\SA-MP-WarZone\pawno\include\nex-ac.inc(2238) : error 017: undefined symbol "STREAMER_PICKUP_SD"
modules\server\server_setup/server_database.pwn(6) : error 017: undefined symbol "ERROR"
modules\server\server_setup/server_database.pwn(7) : error 017: undefined symbol "mysql_connect_file"
modules\server\server_setup/server_database.pwn(7) : warning 213: tag mismatch
modules\server\server_setup/server_database.pwn(9) : warning 213: tag mismatch
modules\server\server_setup/server_database.pwn(14) : error 017: undefined symbol "mysql_error"
modules\server\server_setup/server_database.pwn(14) : warning 202: number of arguments does not match definition
modules\server\server_setup/server_database.pwn(14) : warning 202: number of arguments does not match definition
modules\server\server_setup/server_database.pwn(15) : warning 213: tag mismatch
modules\server\server_setup/server_database.pwn(27) : warning 213: tag mismatch
modules\server\server_setup/server_function.pwn(217) : error 021: symbol already defined: "cache_get_field_content"
modules\server\server_setup/server_function.pwn(220) : error 054: unmatched closing brace ("}")
modules\server\server_setup/server_function.pwn(222) : error 021: symbol already defined: "cache_get_data"
modules\server\server_setup/server_function.pwn(228) : error 021: symbol already defined: "cache_get_row_int"
modules\server\server_setup/server_function.pwn(231) : warning 219: local variable "int_dest" shadows a variable at a preceding level
modules\server\server_setup/server_function.pwn(232) : error 010: invalid function or declaration
modules\server\server_setup/server_function.pwn(253) : error 017: undefined symbol "cache_get_value_name_int"
modules\server\server_setup/server_function.pwn(250) : warning 203: symbol is never used: "row"
modules\player\player_accounts/function.pwn(54) : warning 213: tag mismatch
modules\player\player_accounts/function.pwn(101) : warning 213: tag mismatch
modules\player\player_accounts/dialog.pwn(10) : error 017: undefined symbol "SHA256_PassHash"
modules\player\player_accounts/dialog.pwn(10) : warning 202: number of arguments does not match definition
modules\player\player_accounts/dialog.pwn(55) : error 017: undefined symbol "SHA256_PassHash"
modules\player\player_accounts/dialog.pwn(64) : warning 213: tag mismatch
modules\player\player_class/function.pwn(64) : warning 213: tag mismatch
modules\player\player_class/function.pwn(72) : warning 213: tag mismatch
modules\player\player_class/function.pwn(85) : warning 213: tag mismatch
modules\player\player_class/function.pwn(93) : warning 213: tag mismatch
modules\player\player_clan/callback.pwn(5) : warning 213: tag mismatch
modules\player\player_clan/function.pwn(40) : warning 213: tag mismatch
modules\player\player_clan/function.pwn(71) : warning 213: tag mismatch
modules\player\player_clan/function.pwn(98) : warning 213: tag mismatch
modules\admin\admin_commands/function.pwn(46) : warning 213: tag mismatch
modules\admin\admin_commands/function.pwn(52) : warning 213: tag mismatch
modules\admin\admin_commands/function.pwn(58) : warning 213: tag mismatch
modules\admin\admin_commands/function.pwn(66) : warning 213: tag mismatch
modules\admin\admin_commands/function.pwn(80) : warning 213: tag mismatch
modules\admin\admin_commands/function.pwn(94) : warning 213: tag mismatch
modules\vehicle\vehicle_spawner/cmd.pwn(17) : error 017: undefined symbol "IsValidVehicle"
D:\Server\SA-MP-WarZone\gamemodes\WarZone.pwn(206) : error 017: undefined symbol "IsValidVehicle"
D:\Server\SA-MP-WarZone\gamemodes\WarZone.pwn(458) : warning 203: symbol is never used: "int_dest"
Pawn compiler 3.2.3664	 	 	Copyright (c) 1997-2006, ITB CompuPhase

17 Errors.

Bagaimana cara untuk fix nya? include nya juga kena error

**Comment by AzharHrj** [comment]
Compile nya pake sampctl gan, pake compiler pawno biasa mau sampe kapan pun bakal error

`sampctl p build dev` atau `sampctl package build dev` untuk compile

`sampctl run dev` untuk menjalankan Server nya secara localhost

**Comment by CEKIKOFGAMERS** [comment]
> Compile nya pake sampctl gan, pake compiler pawno biasa mau sampe kapan pun bakal error
> 
> `sampctl p build dev` atau `sampctl package build dev` untuk compile
> 
> `sampctl run dev` untuk menjalankan Server nya secara localhost

Oalah, makasih gan
